package com.goldfish.api;

import com.goldfish.common.CommonResult;
import com.goldfish.web.base.BaseController;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Map;

/**
 * Created by John on 2018/5/20 0020.
 */
public class AjaxCourseController extends BaseController {

    /**
     * 获取学生学习课程
     *
     * {
         "books":[
             {
                 "Id":5,
                 "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
                 "bookName":"零基础入门拼读",
                 "coverImageUrl":"",
                 "totalUnitNbr":17,
                 "currentPosition":{
                     "Id":514981,
                     "studyPositionCode":"68c7bd11-5ebf-4c67-a8c8-e8d3c3b24840",
                     "positionType":0,
                     "vocCode":"8a108cb7-42aa-d911-0142-ad8123f50222",
                     "unitNbr":14,
                     "isCurrentPos":true,
                     "isFinished":0,
                     "spelling":"three",
                     "isAllFinished":true,
                     "IsTested":0,
                     "Status":0
                 },
                 "currentStudyBook":true,
                 "outDate":false,
                 "unitType":"Unit",
                 "startFrom":1,
                 "studyMode":1
             }
         ],
         "condition":0,
         "totalNbr":0,
         "msg":"完成加载",
         "userState":2,
         "totalLoginTimes":0,
         "success":true
     }
     *
     *
     *
     *
     * @param context
     * @return
     */
    @RequestMapping(value="AjaxGetUserBook",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxGetUserBook(ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }

    /**
     * 载入用户课程
     *
     * {
     "books":[
     {
     "Id":5,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "bookName":"零基础入门拼读",
     "coverImageUrl":"",
     "bookState":1,
     "bookType":1,
     "bookPrice":0,
     "currentStudyBook":false,
     "difficultLevel":1,
     "introduce":"0基础4个小时训练掌握拼读",
     "totalUnitNbr":17,
     "CourseUnits":[
     {
     "Id":38,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit1",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":1
     },
     {
     "Id":39,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit2",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":2
     },
     {
     "Id":40,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit3",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":3
     },
     {
     "Id":41,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit4",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":4
     },
     {
     "Id":42,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit5",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":5
     },
     {
     "Id":43,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit6",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":6
     },
     {
     "Id":44,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit7",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":7
     },
     {
     "Id":45,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit8",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":8
     },
     {
     "Id":46,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit9",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":9
     },
     {
     "Id":47,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit10",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":10
     },
     {
     "Id":48,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit11",
     "IsFinished":2,
     "IsTested":2,
     "unitNbr":11
     },
     {
     "Id":49,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit12",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":12
     },
     {
     "Id":50,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit13",
     "IsFinished":2,
     "IsTested":-1,
     "unitNbr":13
     },
     {
     "Id":51,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit14",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":14
     },
     {
     "Id":52,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit15",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":15
     },
     {
     "Id":53,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit16",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":16
     },
     {
     "Id":54,
     "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
     "Unit":"Unit17",
     "IsFinished":2,
     "IsTested":1,
     "unitNbr":17
     }
     ],
     "outDate":false,
     "unitType":"Unit",
     "startFrom":1,
     "studyMode":1,
     "CompleteWordCount":0
     }
     ],
     "condition":0,
     "totalNbr":0,
     "msg":"完成加载",
     "userState":2,
     "totalLoginTimes":0,
     "success":true
     }
     *
     * @param context
     * @return
     */
    @RequestMapping(value="AjaxLoadCourse",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxLoadCourse(ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }

    /**
     * 获取学生单元学习数据
     *
     * {
         "data":[
             {
                 "Id":1460,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812188008d",
                 "spelling":"lick",
                 "meaning":"舔;击败",
                 "soundMarkUs":"[lɪk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":0,
                 "isCollected":false
             },
             {
                 "Id":1461,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812188008e",
                 "spelling":"pick",
                 "meaning":"挑选;拾起",
                 "soundMarkUs":"[pɪk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":1,
                 "isCollected":false
             },
             {
                 "Id":1462,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812189008f",
                 "spelling":"kick",
                 "meaning":"踢;反冲",
                 "soundMarkUs":"[kɪk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":2,
                 "isCollected":false
             },
             {
                 "Id":1463,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121890090",
                 "spelling":"sick",
                 "meaning":"有病的;恶心的",
                 "soundMarkUs":"[sɪk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":3,
                 "isCollected":false
             },
             {
                 "Id":1464,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218a0092",
                 "spelling":"thick",
                 "meaning":"厚的;浓密的;粗的",
                 "soundMarkUs":"[θɪk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":4,
                 "isCollected":false
             },
             {
                 "Id":1465,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218b0093",
                 "spelling":"it",
                 "meaning":"它",
                 "soundMarkUs":"[ɪt]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":5,
                 "isCollected":false
             },
             {
                 "Id":1466,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218b0094",
                 "spelling":"sit",
                 "meaning":"坐",
                 "soundMarkUs":"[sɪt]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":6,
                 "isCollected":false
             },
             {
                 "Id":1467,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218c0095",
                 "spelling":"six",
                 "meaning":"六",
                 "soundMarkUs":"[sɪks]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":7,
                 "isCollected":false
             },
             {
                 "Id":1468,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218c0096",
                 "spelling":"fix",
                 "meaning":"修理;固定",
                 "soundMarkUs":"[fɪks]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":8,
                 "isCollected":false
             },
             {
                 "Id":1469,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218d0097",
                 "spelling":"mix",
                 "meaning":"混合;搅拌",
                 "soundMarkUs":"[mɪks]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":9,
                 "isCollected":false
             },
             {
                 "Id":1470,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218d0099",
                 "spelling":"with",
                 "meaning":"和....",
                 "soundMarkUs":"[wɪð]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":10,
                 "isCollected":false
             },
             {
                 "Id":1471,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218e009a",
                 "spelling":"him",
                 "meaning":"他",
                 "soundMarkUs":"[hɪm]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":11,
                 "isCollected":false
             },
             {
                 "Id":1472,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81218f009d",
                 "spelling":"give",
                 "meaning":"给出",
                 "soundMarkUs":"[ɡɪv]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":12,
                 "isCollected":false
             },
             {
                 "Id":1473,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812190009e",
                 "spelling":"dig",
                 "meaning":"挖掘",
                 "soundMarkUs":"[dɪɡ]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":13,
                 "isCollected":false
             },
             {
                 "Id":1474,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812190009f",
                 "spelling":"pig",
                 "meaning":"猪",
                 "soundMarkUs":"[pɪɡ]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":14,
                 "isCollected":false
             },
             {
                 "Id":1475,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ac00a0",
                 "spelling":"pin",
                 "meaning":"大头针",
                 "soundMarkUs":"[pɪn]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":15,
                 "isCollected":false
             },
             {
                 "Id":1476,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ac00a1",
                 "spelling":"inn",
                 "meaning":"旅馆;客栈",
                 "soundMarkUs":"[ɪn]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":16,
                 "isCollected":false
             },
             {
                 "Id":1477,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ad00a2",
                 "spelling":"ink",
                 "meaning":"墨水",
                 "soundMarkUs":"[ɪŋk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":17,
                 "isCollected":false
             },
             {
                 "Id":1478,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ad00a3",
                 "spelling":"pink",
                 "meaning":"粉红色的",
                 "soundMarkUs":"[pɪŋk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":18,
                 "isCollected":false
             },
             {
                 "Id":1479,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ae00a4",
                 "spelling":"link",
                 "meaning":"联系;链接",
                 "soundMarkUs":"[lɪŋk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":19,
                 "isCollected":false
             },
             {
                 "Id":1480,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ae00a5",
                 "spelling":"think",
                 "meaning":"思考;认为",
                 "soundMarkUs":"[θɪŋk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":20,
                 "isCollected":false
             },
             {
                 "Id":1481,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121ae00a6",
                 "spelling":"bill",
                 "meaning":"账单",
                 "soundMarkUs":"[bɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":21,
                 "isCollected":false
             },
             {
                 "Id":1482,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121af00a7",
                 "spelling":"hill",
                 "meaning":"小山",
                 "soundMarkUs":"[hɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":22,
                 "isCollected":false
             },
             {
                 "Id":1483,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121af00a8",
                 "spelling":"kill",
                 "meaning":"杀死",
                 "soundMarkUs":"[kɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":23,
                 "isCollected":false
             },
             {
                 "Id":1484,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b000a9",
                 "spelling":"pill",
                 "meaning":"药片;药丸",
                 "soundMarkUs":"[pɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":24,
                 "isCollected":false
             },
             {
                 "Id":1485,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b000aa",
                 "spelling":"still",
                 "meaning":"静止的;仍然",
                 "soundMarkUs":"[stɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":25,
                 "isCollected":false
             },
             {
                 "Id":1486,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b100ab",
                 "spelling":"will",
                 "meaning":"将要;决心;遗产",
                 "soundMarkUs":"[wɪl]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":26,
                 "isCollected":false
             },
             {
                 "Id":1487,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b100ac",
                 "spelling":"milk",
                 "meaning":"牛奶;挤牛奶",
                 "soundMarkUs":"[mɪlk]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":27,
                 "isCollected":false
             },
             {
                 "Id":1488,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b300ae",
                 "spelling":"film",
                 "meaning":"电影;拍电影",
                 "soundMarkUs":"[fɪlm]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":28,
                 "isCollected":false
             },
             {
                 "Id":1489,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b300af",
                 "spelling":"kiss",
                 "meaning":"吻",
                 "soundMarkUs":"[kɪs]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":29,
                 "isCollected":false
             },
             {
                 "Id":1490,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121b400b0",
                 "spelling":"Miss",
                 "meaning":"小姐;女士",
                 "soundMarkUs":"[mɪs]",
                 "soundMarkUk":"",
                 "UnitId":0,
                 "unitNbr":3,
                 "lessonNbr":5,
                 "fstClassId":8,
                 "vocIndex":30,
                 "isCollected":false
             }
         ],
         "success":true,
         "condition":0,
         "msg":"搞定！",
         "studytoken":"c06616b5-4ca2-432a-ab94-50261c50baca",
         "bookInfo":{
             "Id":5,
             "moduleCode":"8a108cb7-42ad-314f-0142-ad33a0a70001",
             "bookName":"零基础入门拼读",
             "coverImageUrl":"",
             "totalUnitNbr":17,
             "outDate":false,
             "startFrom":0,
             "studyMode":0
         },
         "studyPos":{
             "Id":513527,
             "studyPositionCode":"e2b18f0b-bdd2-4413-9dc1-d305d3efaf7e",
             "positionType":0,
             "vocCode":"8a108cb7-42aa-d911-0142-ad81218b0093",
             "unitNbr":3,
             "isCurrentPos":true,
             "isFinished":0,
             "spelling":"it",
             "isAllFinished":false,
             "IsTested":0,
             "Status":0
         },
         "totalNbr":0
     }
     *
     *
     *
     * @param context
     * @return
     */
    @RequestMapping(value="AjaxGetUnit",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxGetUnit(ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }


    /**
     * 保存课程单元学习
     * {
     "success":false,
     "msg":"没有记录需要提交",
     "isFinished":2,
     "latestStudyPosition":"{"Id":0,"studyPositionCode":null,"studytoken":null,"moduleCode":null,"positionType":null,"remark":null,"vocCode":null,"totalReadingTime":null,"totalWritingTime":null,"userCode":null,"unitNbr":null,"wordCount":null,"isContinue":null,"seconds4SpellingLetter":null,"isCurrentPos":false,"isFinished":2,"spelling":null,"isAllFinished":false,"createtime":null,"IsTested":0,"Status":0}"
     }

     moduleCode:8a108cb7-42ad-314f-0142-ad33a0a70001
     extra:finish
     unitNbr:1
     studytoken:007c3778-11b1-4edb-ba5f-d550bc11516d
     isContinue:0
     seconds4SpellingLetter:1000
     totalReadingTime:86
     totalWritingTime:99
     vocDataAfterReview:[
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":4.375,
     "isFstReadSuccess":false,
     "readFailTimes":3,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120300028"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120310029"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":false,
     "spellFailTimes":1,
     "continueSpellFailTimes":0,
     "isHalfSpelling":true,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad812031002a"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":false,
     "spellFailTimes":1,
     "continueSpellFailTimes":0,
     "isHalfSpelling":true,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad812032002b"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120350030"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":1.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120380034"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120380035"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120410036"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":2,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120420038"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120420039"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":1.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad812043003a"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad812043003b"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81208d003c"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81208d003d"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81208e003e"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":1.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81208e003f"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81208f0040"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120900042"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120900043"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120910044"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":1.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120930047"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad812094004a"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81209d004b"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81209d004c"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81209e004e"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":1.5,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad81209f004f"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d20051"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d30052"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d30053"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d40054"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":2.5,
     "isFstReadSuccess":false,
     "readFailTimes":1,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d50055"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d50056"
     },
     {
     "memoryLevel":null,
     "reviewTimes":null,
     "timeLeft":null,
     "userVocCode":null,
     "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
     "finishReadingTime":0,
     "isFstReadSuccess":true,
     "readFailTimes":0,
     "continueReadFailTimes":0,
     "isHalfReading":false,
     "isFstSpellSuccess":true,
     "spellFailTimes":0,
     "continueSpellFailTimes":0,
     "isHalfSpelling":false,
     "isRemember":true,
     "isCancelReview":false,
     "vocCode":"8a108cb7-42aa-d911-0142-ad8120d60057"
     }
     ]
     totalWordsNbr:33

     响应报文

     {
     "success":true,
     "msg":"提交成功",
     "latestStudyPosition":"[{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120300028","finishReadingTime":4.375,"isFstReadSuccess":false,"readFailTimes":3,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120310029","finishReadingTime":0.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad812031002a","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":false,"spellFailTimes":1,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":true,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad812032002b","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":false,"spellFailTimes":1,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":true,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120350030","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120380034","finishReadingTime":1.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120380035","finishReadingTime":0.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120410036","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120420038","finishReadingTime":2.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120420039","finishReadingTime":0.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad812043003a","finishReadingTime":1.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad812043003b","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81208d003c","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81208d003d","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81208e003e","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81208e003f","finishReadingTime":1.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81208f0040","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120900042","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120900043","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120910044","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120930047","finishReadingTime":1.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad812094004a","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81209d004b","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81209d004c","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81209e004e","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad81209f004f","finishReadingTime":1.5,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d20051","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d30052","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d30053","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d40054","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d50055","finishReadingTime":2.5,"isFstReadSuccess":false,"readFailTimes":1,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d50056","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null},{"Id":0,"userVocCode":null,"studyToken":null,"userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b","vocCode":"8a108cb7-42aa-d911-0142-ad8120d60057","finishReadingTime":0.0,"isFstReadSuccess":true,"readFailTimes":0,"continueReadFailTimes":0,"isFstSpellSuccess":true,"spellFailTimes":0,"continueSpellFailTimes":0,"isHalfReading":false,"isHalfSpelling":false,"remark":null,"startTime":null,"lastReviewTime":"0001-01-01T00:00:00","lastComputeTime":null,"IsRemember":true,"IsCancelReview":false,"ceatetime":null,"reviewTimes":null,"memoryLevel":null,"timeLeft":null,"Status":null}]",
     "cashPoint":1
     }




     *
     * @param context
     * @return
     */
    @RequestMapping(value="AjaxInterruptSaveUnit",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxInterruptSaveUnit(String moduleCode, String extra, Integer unitNbr, String vocCode,
                                               String studyToken, Long totalReadingTime, Long totalWritingTime,
                                               String vocDataAfterReview,Integer totalnum, ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }
}
