package com.goldfish.api;

import com.goldfish.common.CommonResult;
import com.goldfish.web.base.BaseController;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.Map;

/**
 * Created by John on 2018/5/20 0020.
 */
public class AjaxErrorBookController extends AjaxReviewBookController{

    /**
     * TODO:错词单词学习
     *
     *
     * {
         "data":[
             {
                 "Id":1516,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121f500d4",
                 "spelling":"dame",
                 "soundMark":"",
                 "meaning":"夫人（女爵）",
                 "soundMarkUs":"[deɪm]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":0,
                 "isCollected":false
             },
             {
                 "Id":1518,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121f500d6",
                 "spelling":"game",
                 "soundMark":"",
                 "meaning":"游戏;赌博",
                 "soundMarkUs":"[ɡeɪm]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":1,
                 "isCollected":false
             },
             {
                 "Id":1522,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121f700da",
                 "spelling":"bake",
                 "soundMark":"",
                 "meaning":"烘烤",
                 "soundMarkUs":"[beɪk]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":2,
                 "isCollected":false
             },
             {
                 "Id":1523,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8121f800db",
                 "spelling":"cake",
                 "soundMark":"",
                 "meaning":"蛋糕",
                 "soundMarkUs":"[keɪk]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":3,
                 "isCollected":false
             },
             {
                 "Id":1524,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81221100dc",
                 "spelling":"fake",
                 "soundMark":"",
                 "meaning":"假的;伪造的",
                 "soundMarkUs":"[feɪk]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":4,
                 "isCollected":false
             },
             {
                 "Id":1564,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122620110",
                 "spelling":"mice",
                 "soundMark":"",
                 "meaning":"老鼠（复数）",
                 "soundMarkUs":"[maɪs]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":5,
                 "isCollected":false
             },
             {
                 "Id":1565,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122620111",
                 "spelling":"nice",
                 "soundMark":"",
                 "meaning":"好的，漂亮",
                 "soundMarkUs":"[naɪs]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":6,
                 "isCollected":false
             },
             {
                 "Id":1566,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122630112",
                 "spelling":"rice",
                 "soundMark":"",
                 "meaning":"米饭",
                 "soundMarkUs":"[raɪs]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":7,
                 "isCollected":false
             },
             {
                 "Id":1567,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122630113",
                 "spelling":"ride",
                 "soundMark":"",
                 "meaning":"骑 ;乘",
                 "soundMarkUs":"[raɪd]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":8,
                 "isCollected":false
             },
             {
                 "Id":1569,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122640115",
                 "spelling":"side",
                 "soundMark":"",
                 "meaning":"边;边缘",
                 "soundMarkUs":"[saɪd]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":9,
                 "isCollected":false
             },
             {
                 "Id":1570,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122650117",
                 "spelling":"drive",
                 "soundMark":"",
                 "meaning":"驾驶",
                 "soundMarkUs":"[draɪv]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":10,
                 "isCollected":false
             },
             {
                 "Id":1576,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81227f0122",
                 "spelling":"cube",
                 "soundMark":"",
                 "meaning":"立方",
                 "soundMarkUs":"[kjuːb]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":11,
                 "isCollected":false
             },
             {
                 "Id":1578,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122800124",
                 "spelling":"huge",
                 "soundMark":"",
                 "meaning":"巨大的",
                 "soundMarkUs":"[hjuːdʒ]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":12,
                 "isCollected":false
             },
             {
                 "Id":1579,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122810126",
                 "spelling":"tube",
                 "soundMark":"",
                 "meaning":"管子",
                 "soundMarkUs":"[tjuːb]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":13,
                 "isCollected":false
             },
             {
                 "Id":1580,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122810127",
                 "spelling":"tail",
                 "soundMark":"",
                 "meaning":"尾巴;辫子",
                 "soundMarkUs":"[teɪl]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":14,
                 "isCollected":false
             },
             {
                 "Id":1583,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812283012a",
                 "spelling":"nail",
                 "soundMark":"",
                 "meaning":"指甲;钉;爪",
                 "soundMarkUs":"[neɪl]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":15,
                 "isCollected":false
             },
             {
                 "Id":1584,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812283012b",
                 "spelling":"maid",
                 "soundMark":"",
                 "meaning":"少女;女仆",
                 "soundMarkUs":"[meɪd]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":16,
                 "isCollected":false
             },
             {
                 "Id":1585,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad812299012c",
                 "spelling":"rain",
                 "soundMark":"",
                 "meaning":"下雨",
                 "soundMarkUs":"[reɪn]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":17,
                 "isCollected":false
             },
             {
                 "Id":1586,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81229a012d",
                 "spelling":"pain",
                 "soundMark":"",
                 "meaning":"疼痛",
                 "soundMarkUs":"[peɪn]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":18,
                 "isCollected":false
             },
             {
                 "Id":1587,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81229a012e",
                 "spelling":"paint",
                 "soundMark":"",
                 "meaning":"绘画",
                 "soundMarkUs":"[peɪnt]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":19,
                 "isCollected":false
             },
             {
                 "Id":1590,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81229b0131",
                 "spelling":"hay",
                 "soundMark":"",
                 "meaning":"干草",
                 "soundMarkUs":"[heɪ]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":20,
                 "isCollected":false
             },
             {
                 "Id":1613,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122be014d",
                 "spelling":"seat",
                 "soundMark":"",
                 "meaning":"座位;所在地",
                 "soundMarkUs":"[siːt]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":21,
                 "isCollected":false
             },
             {
                 "Id":1614,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122bf014f",
                 "spelling":"peanut",
                 "soundMark":"",
                 "meaning":"花生",
                 "soundMarkUs":"['piːnʌt]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":22,
                 "isCollected":false
             },
             {
                 "Id":1615,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122c00150",
                 "spelling":"eagle",
                 "soundMark":"",
                 "meaning":"老鹰",
                 "soundMarkUs":"['iːɡl]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":23,
                 "isCollected":false
             },
             {
                 "Id":1621,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122d90156",
                 "spelling":"sigh",
                 "soundMark":"",
                 "meaning":"叹息",
                 "soundMarkUs":"[saɪ]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":24,
                 "isCollected":false
             },
             {
                 "Id":1625,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122db015a",
                 "spelling":"fight",
                 "soundMark":"",
                 "meaning":"战斗;打架",
                 "soundMarkUs":"[faɪt]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":25,
                 "isCollected":false
             },
             {
                 "Id":1650,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8122fb0176",
                 "spelling":"window",
                 "soundMark":"",
                 "meaning":"窗户",
                 "soundMarkUs":"['wɪndəʊ]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":26,
                 "isCollected":false
             },
             {
                 "Id":1665,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8123190188",
                 "spelling":"fruit",
                 "soundMark":"",
                 "meaning":"果实;成果;水果",
                 "soundMarkUs":"[fruːt]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":27,
                 "isCollected":false
             },
             {
                 "Id":1713,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81237401c3",
                 "spelling":"tower",
                 "soundMark":"",
                 "meaning":"塔;高楼;高耸;胜过",
                 "soundMarkUs":"['taʊə(r)]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":28,
                 "isCollected":false
             },
             {
                 "Id":1714,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81237501c4",
                 "spelling":"towel",
                 "soundMark":"",
                 "meaning":"毛巾;手巾",
                 "soundMarkUs":"['taʊəl]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":29,
                 "isCollected":false
             },
             {
                 "Id":1716,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81237601c6",
                 "spelling":"clown",
                 "soundMark":"",
                 "meaning":"小丑;粗鲁愚蠢的人",
                 "soundMarkUs":"[klaʊn]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":30,
                 "isCollected":false
             },
             {
                 "Id":1718,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81237701c8",
                 "spelling":"crown",
                 "soundMark":"",
                 "meaning":"王冠;王权;花冠;",
                 "soundMarkUs":"[kraʊn]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":31,
                 "isCollected":false
             },
             {
                 "Id":1785,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8123e00213",
                 "spelling":"whistle",
                 "soundMark":"",
                 "meaning":"口哨;汽笛;警笛",
                 "soundMarkUs":"['wɪsl]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":32,
                 "isCollected":false
             },
             {
                 "Id":1796,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8123f50220",
                 "spelling":"leather",
                 "soundMark":"",
                 "meaning":"皮革",
                 "soundMarkUs":"['leðə(r)]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":33,
                 "isCollected":false
             },
             {
                 "Id":1875,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad8124670282",
                 "spelling":"prawn",
                 "soundMark":"",
                 "meaning":"对虾;明虾",
                 "soundMarkUs":"[prɔːn]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":34,
                 "isCollected":false
             },
             {
                 "Id":1895,
                 "vocCode":"8a108cb7-42aa-d911-0142-ad81247f029c",
                 "spelling":"address",
                 "soundMark":"",
                 "meaning":"地址;称呼;发表演说",
                 "soundMarkUs":"[ə'dres]",
                 "UnitId":0,
                 "unitNbr":1,
                 "vocIndex":35,
                 "isCollected":false
             }
         ],
         "success":true,
         "condition":0,
         "msg":"搞定！",
         "studytoken":"7b4db6fd-316c-4dc3-8ea8-47e0f560ebce",
         "bookInfo":{
             "Id":0,
             "moduleCode":"00000000-0000-0000-0000-000000000000",
             "bookName":"错词强化学...",
             "totalUnitNbr":0,
             "outDate":false,
             "startFrom":0,
             "studyMode":0
         },
         "totalNbr":0
     }
     */

    /**
     *
     * @param moduleCode 00000000-0000-0000-0000-000000000000
     * @param unit 1
     * @param context
     * @return
     *
     * {
    "data":[
    {
    "Id":1436,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81211b0070",
    "spelling":"rend",
    "soundMark":"",
    "meaning":"撕破;分裂",
    "soundMarkUs":"[rend]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":0,
    "isCollected":false
    },
    {
    "Id":1465,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81218b0093",
    "spelling":"it",
    "soundMark":"",
    "meaning":"它",
    "soundMarkUs":"[ɪt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":1,
    "isCollected":false
    },
    {
    "Id":1511,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8121f200cf",
    "spelling":"cape",
    "soundMark":"",
    "meaning":"海角;披肩",
    "soundMarkUs":"[keɪp]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":2,
    "isCollected":false
    },
    {
    "Id":1512,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8121f300d0",
    "spelling":"gape",
    "soundMark":"",
    "meaning":"裂口;张嘴;打哈欠",
    "soundMarkUs":"[ɡeɪp]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":3,
    "isCollected":false
    },
    {
    "Id":1513,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8121f300d1",
    "spelling":"tape",
    "soundMark":"",
    "meaning":"磁带;录音;用胶布粘",
    "soundMarkUs":"[teɪp]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":4,
    "isCollected":false
    },
    {
    "Id":1564,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122620110",
    "spelling":"mice",
    "soundMark":"",
    "meaning":"老鼠（复数）",
    "soundMarkUs":"[maɪs]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":5,
    "isCollected":false
    },
    {
    "Id":1565,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122620111",
    "spelling":"nice",
    "soundMark":"",
    "meaning":"好的，漂亮",
    "soundMarkUs":"[naɪs]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":6,
    "isCollected":false
    },
    {
    "Id":1566,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122630112",
    "spelling":"rice",
    "soundMark":"",
    "meaning":"米饭",
    "soundMarkUs":"[raɪs]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":7,
    "isCollected":false
    },
    {
    "Id":1567,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122630113",
    "spelling":"ride",
    "soundMark":"",
    "meaning":"骑 ;乘",
    "soundMarkUs":"[raɪd]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":8,
    "isCollected":false
    },
    {
    "Id":1569,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122640115",
    "spelling":"side",
    "soundMark":"",
    "meaning":"边;边缘",
    "soundMarkUs":"[saɪd]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":9,
    "isCollected":false
    },
    {
    "Id":1570,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122650117",
    "spelling":"drive",
    "soundMark":"",
    "meaning":"驾驶",
    "soundMarkUs":"[draɪv]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":10,
    "isCollected":false
    },
    {
    "Id":1576,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81227f0122",
    "spelling":"cube",
    "soundMark":"",
    "meaning":"立方",
    "soundMarkUs":"[kjuːb]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":11,
    "isCollected":false
    },
    {
    "Id":1578,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122800124",
    "spelling":"huge",
    "soundMark":"",
    "meaning":"巨大的",
    "soundMarkUs":"[hjuːdʒ]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":12,
    "isCollected":false
    },
    {
    "Id":1579,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122810126",
    "spelling":"tube",
    "soundMark":"",
    "meaning":"管子",
    "soundMarkUs":"[tjuːb]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":13,
    "isCollected":false
    },
    {
    "Id":1580,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122810127",
    "spelling":"tail",
    "soundMark":"",
    "meaning":"尾巴;辫子",
    "soundMarkUs":"[teɪl]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":14,
    "isCollected":false
    },
    {
    "Id":1583,
    "vocCode":"8a108cb7-42aa-d911-0142-ad812283012a",
    "spelling":"nail",
    "soundMark":"",
    "meaning":"指甲;钉;爪",
    "soundMarkUs":"[neɪl]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":15,
    "isCollected":false
    },
    {
    "Id":1584,
    "vocCode":"8a108cb7-42aa-d911-0142-ad812283012b",
    "spelling":"maid",
    "soundMark":"",
    "meaning":"少女;女仆",
    "soundMarkUs":"[meɪd]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":16,
    "isCollected":false
    },
    {
    "Id":1585,
    "vocCode":"8a108cb7-42aa-d911-0142-ad812299012c",
    "spelling":"rain",
    "soundMark":"",
    "meaning":"下雨",
    "soundMarkUs":"[reɪn]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":17,
    "isCollected":false
    },
    {
    "Id":1586,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81229a012d",
    "spelling":"pain",
    "soundMark":"",
    "meaning":"疼痛",
    "soundMarkUs":"[peɪn]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":18,
    "isCollected":false
    },
    {
    "Id":1587,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81229a012e",
    "spelling":"paint",
    "soundMark":"",
    "meaning":"绘画",
    "soundMarkUs":"[peɪnt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":19,
    "isCollected":false
    },
    {
    "Id":1590,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81229b0131",
    "spelling":"hay",
    "soundMark":"",
    "meaning":"干草",
    "soundMarkUs":"[heɪ]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":20,
    "isCollected":false
    },
    {
    "Id":1613,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122be014d",
    "spelling":"seat",
    "soundMark":"",
    "meaning":"座位;所在地",
    "soundMarkUs":"[siːt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":21,
    "isCollected":false
    },
    {
    "Id":1614,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122bf014f",
    "spelling":"peanut",
    "soundMark":"",
    "meaning":"花生",
    "soundMarkUs":"['piːnʌt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":22,
    "isCollected":false
    },
    {
    "Id":1615,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122c00150",
    "spelling":"eagle",
    "soundMark":"",
    "meaning":"老鹰",
    "soundMarkUs":"['iːɡl]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":23,
    "isCollected":false
    },
    {
    "Id":1621,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122d90156",
    "spelling":"sigh",
    "soundMark":"",
    "meaning":"叹息",
    "soundMarkUs":"[saɪ]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":24,
    "isCollected":false
    },
    {
    "Id":1625,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122db015a",
    "spelling":"fight",
    "soundMark":"",
    "meaning":"战斗;打架",
    "soundMarkUs":"[faɪt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":25,
    "isCollected":false
    },
    {
    "Id":1650,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8122fb0176",
    "spelling":"window",
    "soundMark":"",
    "meaning":"窗户",
    "soundMarkUs":"['wɪndəʊ]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":26,
    "isCollected":false
    },
    {
    "Id":1665,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8123190188",
    "spelling":"fruit",
    "soundMark":"",
    "meaning":"果实;成果;水果",
    "soundMarkUs":"[fruːt]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":27,
    "isCollected":false
    },
    {
    "Id":1713,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81237401c3",
    "spelling":"tower",
    "soundMark":"",
    "meaning":"塔;高楼;高耸;胜过",
    "soundMarkUs":"['taʊə(r)]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":28,
    "isCollected":false
    },
    {
    "Id":1714,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81237501c4",
    "spelling":"towel",
    "soundMark":"",
    "meaning":"毛巾;手巾",
    "soundMarkUs":"['taʊəl]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":29,
    "isCollected":false
    },
    {
    "Id":1716,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81237601c6",
    "spelling":"clown",
    "soundMark":"",
    "meaning":"小丑;粗鲁愚蠢的人",
    "soundMarkUs":"[klaʊn]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":30,
    "isCollected":false
    },
    {
    "Id":1718,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81237701c8",
    "spelling":"crown",
    "soundMark":"",
    "meaning":"王冠;王权;花冠;",
    "soundMarkUs":"[kraʊn]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":31,
    "isCollected":false
    },
    {
    "Id":1785,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8123e00213",
    "spelling":"whistle",
    "soundMark":"",
    "meaning":"口哨;汽笛;警笛",
    "soundMarkUs":"['wɪsl]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":32,
    "isCollected":false
    },
    {
    "Id":1875,
    "vocCode":"8a108cb7-42aa-d911-0142-ad8124670282",
    "spelling":"prawn",
    "soundMark":"",
    "meaning":"对虾;明虾",
    "soundMarkUs":"[prɔːn]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":33,
    "isCollected":false
    },
    {
    "Id":1895,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81247f029c",
    "spelling":"address",
    "soundMark":"",
    "meaning":"地址;称呼;发表演说",
    "soundMarkUs":"[ə'dres]",
    "UnitId":0,
    "unitNbr":1,
    "vocIndex":34,
    "isCollected":false
    }
    ],
    "success":true,
    "condition":0,
    "msg":"搞定！",
    "studytoken":"7013d630-4b89-4c9a-8999-e635c5ca6814",
    "bookInfo":{
    "Id":0,
    "moduleCode":"00000000-0000-0000-0000-000000000000",
    "bookName":"错词强化学...",
    "totalUnitNbr":0,
    "outDate":false,
    "startFrom":0,
    "studyMode":0
    },
    "studyPos":{
    "Id":514543,
    "studyPositionCode":"6ced823a-7526-4da6-b212-fd2a4a6dda7d",
    "studytoken":"8f8a1f05-0450-478d-b1c9-fb32218c93a2",
    "moduleCode":"00000000-0000-0000-0000-000000000000",
    "positionType":3,
    "vocCode":"8a108cb7-42aa-d911-0142-ad81218b0093",
    "totalReadingTime":3,
    "totalWritingTime":3,
    "userCode":"f4f18fcf-c36c-49a3-a23e-a751c0743d4b",
    "unitNbr":1,
    "wordCount":0,
    "isCurrentPos":false,
    "spelling":"it",
    "isAllFinished":false,
    "createtime":"2018-04-30 10:50:57",
    "IsTested":0,
    "Status":1
    },
    "totalNbr":0
    }
     */
    @RequestMapping(value="AjaxGetErrorUnit",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxGetErrorUnit(String moduleCode,
                                          Integer unit, ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }

    /**
     *
     * {
         "data":[

         ],
         "success":true,
         "condition":0,
         "studytoken":"00000000-0000-0000-0000-000000000000",
         "totalNbr":0
     }
     * @param context
     * @return
     */
    @RequestMapping(value="AjaxGetErrorBook",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxGetErrorBook(String orderType, Integer start, Integer limit, ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }

    /**
     * 错题本计数
     * @param orderType
     * @param context
     * @return
     */
    @RequestMapping(value="GetErrorBookCount",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doGetErrorBookCount(String orderType, ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }

    /**
     * TODO:错词本学习保存
     *
     * {"success":true,"condition":0,"msg":"完成加载","studytoken":"5918ba12-1b0b-4103-bb3b-dc0d2e036395","totalNbr":0}
     *
     * @param context
     * @return
     */

    /**
     * 保存错词本学习
     * @param moduleCode 00000000-0000-0000-0000-000000000000
     * @param extra dontdelete
     * @param unitNbr 1
     * @param vocCode 8a108cb7-42aa-d911-0142-ad81218b0093
     * @param studytoken 7013d630-4b89-4c9a-8999-e635c5ca6814
     * @param totalReadingTime 38
     * @param totalWritingTime 0
     * @param vocDataAfterReview []
     * @param context
     * @return
     *
     * {
    "success":false,
    "msg":"",
    "isFinished":2,
    "latestStudyPosition":"{"Id":0,"studyPositionCode":null,"studytoken":null,"moduleCode":null,"positionType":null,"remark":null,"vocCode":null,"totalReadingTime":null,"totalWritingTime":null,"userCode":null,"unitNbr":null,"wordCount":null,"isContinue":null,"seconds4SpellingLetter":null,"isCurrentPos":false,"isFinished":2,"spelling":null,"isAllFinished":false,"createtime":null,"IsTested":0,"Status":0}"
    }
     */
    @RequestMapping(value="AjaxErrorStudySave",method={RequestMethod.GET,RequestMethod.POST})
    public @ResponseBody
    Map<String,Object> doAjaxErrorStudySave(String moduleCode, String extra,
                                            Integer unitNbr, String vocCode,
                                            String studytoken,
                                            Long totalReadingTime, Long totalWritingTime,
                                            String vocDataAfterReview, ModelMap context) {
        CommonResult result = null;
        return result.getReturnMap();
    }



}
